#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <assert.h>
#include <stdbool.h>
#include <time.h>
#include "global.c"
#include "system.c"
#include "list.c"
#include "key.c"
#include "permutation.c"
#include "text.c"
#include "print.c"
#include "encode.c"
#include "main.c"